# Study info
study_name: BrynnHonours
task: bci
data_type: eeg
# Ethics board name and protocol ID
reb_info: Dalhousie SSHREB 2019-4770
# add additional project team member names
authors:
  - Aaron J. Newman
  - Brynn Harris-Shanks
  - Max Mascini
# Specify source of study funding ('NSERC', 'SSHRC', etc.)
funding: NSERC

# EEG recording details
amp_mfr: BrainVision
amp_model: actiCHamp
sw_filt:
  - Highpass filter:
      - half-amplitude cutoff (Hz): .01
  - Lowpass filter:
      - half-amplitude cutoff (Hz): 130
hw_filt:
  - Anti-aliasing filter:
    - half-amplitude cutoff (Hz): 130
    - rolloff: 3dB per octave 
eeg_ref: average
eeg_ground: FCz
cap_mfr: BrainVision
cap_model: ActiCap
eog:
  - HEOG
  - VEOG
montage_fname: standard_1005

# Lab Info - should be the same for all studies
line_freq: 60
instn: Dalhousie University
instn_addr: Halifax, NS, Canada
instn_dept: NeuroCognitive Imaging Lab, Department of Psychology & Neuroscience
license: BSD 3-clause

# Events (can get long)
# event_id:
#   - 'Neutral/Inverted/Standard/L1'
#     - 211
  #     - 'Neutral/Upright/Standard/L1':221
  #     - 'Neutral/Inverted/Standard/L2':212
  #     - 'Neutral/Upright/Standard/L2':222
  #     - 'Neutral/Inverted/Standard/L3':213
  #     - 'Neutral/Upright/Standard/L3':223
  #     - 'Neutral/Inverted/Standard/L4':214
  #     - 'Neutral/Upright/Standard/L4':224
  #     - 'Neutral/Inverted/Standard/L5':215
  #     - 'Neutral/Upright/Standard/L5':225
  #     - 'Neutral/Inverted/Standard/L6':216
  #     - 'Neutral/Upright/Standard/L6':226
  #     - 'Green/Inverted/Standard/L1':111
  #     - 'Green/Upright/Standard/L1':121
  #     - 'Green/Inverted/Standard/L2':112
  #     - 'Green/Upright/Standard/L2':122
  #     - 'Green/Inverted/Standard/L3':113
  #     - 'Green/Upright/Standard/L3':123
  #     - 'Green/Inverted/Standard/L4':114
  #     - 'Green/Upright/Standard/L4':124
  #     - 'Green/Inverted/Standard/L5':115
  #     - 'Green/Upright/Standard/L5':125
  #     - 'Green/Inverted/Standard/L6':116
  #     - 'Green/Upright/Standard/L6':126
  #     - 'Cue/L1':191
  #     - 'Cue/L2':192
  #     - 'Cue/L3':193
  #     - 'Cue/L4':194
  #     - 'Cue/L5':195
  #     - 'Cue/L6':196
  
# ERP preprocessing parameters
preprocessing_settings:
  filter:
    - n_jobs: -1
    - l_freq: 0.1
    - l_freq_ica: 1.
    - h_freq: 30.0
    - filter_picks:
      - eeg
      - eog

  ica:
    - ica_random_state: 42  # seed so ICA is reproducable each time its run
    - n_components: .95     # Specify n_components as a decimal to set % explained variance
    - tstep: 1.0
    - ica_zthresh: 3
    - ica_zstep: .05
    - n_min_eog: 1

  # note that a blank value is mapped to None type in Python
  # In contrast, putting None in this file results in a string in Python (not what you want)
  epoch:
    - tmin: -0.200  # start of each epoch (in sec)
    - tmax:  0.500  # end of each epoch (in sec)
    - baseline: 
        - -0.100
        - 0
    - detrend: 1
    - reject: 
    - flat: 
    - rereference: average
    - tshift: 0.0062

analysis_settings:
  - t_min: -0.100
  - t_max: 0.500
  - baseline: (None, 0)
  - tshift: 0.0062

rois: 
  - vertex:
    - C3, Cz, C4, CP1, CPz, CP2, Pz
  - left:
    - CP5, P3, P7, PO7, PO3
  - right:
    - CP6, P4, P8, PO8, PO4

components:
  n170:
    t_min: -0.100
    t_max: .700
    baseline: (-0.100, 0)
    reference: average
    rois:
      - left
      - right
    peak_lat: 0.190
    tw_width: .050
    tw_range: 
        - .090
        - .290
    component_meas: neg
  
  p300:
    t_min: -0.100
    t_max: .700
    baseline: (-0.100, 0)
    reference: average
    rois:
      - left
      - right
    peak_lat: 0.300
    tw_width: .050
    tw_range: 
        - .250
        - .350
    component_meas: neg
  
classification:
  - test_size: .20
